name = "austrian-currents"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "GENERATION_CACHE"
id = "f71351adc0e2425ba9440f534c8b1687"
preview_id = "79db96262aaa466b90d934673aee3fef"
